// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numOfTests = Integer.parseInt(args[0]);
		// must assign a value to them as we use them later on
		int countOverHalf = 0, countUnderHalf = 0; 
		// loop to generate random numbers for uniform check
		for (int i = 0; i < numOfTests; i++) {
			double random = Math.random();
			if (random > 0.5) {
				countOverHalf++;
			}
			else {
				countUnderHalf++;
			}
		}
		
		// edge case
		if (countOverHalf == 0 || countUnderHalf == 0) {
			System.out.println("> 0.5: " + countOverHalf + " times");
			System.out.println("<= 0.5: " + countUnderHalf + " times");
		}
		else {
			System.out.println("> 0.5: " + countOverHalf + " times");
			System.out.println("<= 0.5: " + countUnderHalf + " times");
			System.out.println("Ratio: " + (double) countOverHalf / countUnderHalf);
		}
		
	}
}
